# May 22, 2025
# Functions Day 1 Building a MadLib (or Haiku, per the Homework 2).

"""Original Chat GPT PROMPT
Please create me a mad lib about a witch 
going to a cat convention with black cat 
that can talk in order to win prize money 
for botox injections, 
give me about 7 words to substitute."""

# Mad Lib: User Inputs.
adj = input("Enter an adjective (e.g., spooky, glamorous): ")
w_name = input("Enter a witch's name (e.g., Grizelda, Moonshadow): ")
clothing = input("Enter an article of clothing (e.g., cloak, sequined hat): ")
c_name = input("Enter a cat's name (e.g., Midnight, Sir Hiss-a-lot): ")
verb = input("Enter a verb (e.g., dance, sing, twerk): ")
money = input("Enter an amount of money (e.g., $5,000, one million dollars): ")
enhance = input("Enter a body enhancement procedure (e.g., botox, lip filler): ")

# Story.
story = f'''
Mad Lib: "Witch & Whiskers: The Botox Heist"

Once upon a {adj} night, a witch named {w_name} dusted off her best {clothing} and headed to the Annual Cat Convention. 
Her sleek black cat, {c_name}, who could {verb} and speak fluent sarcasm, strutted alongside her.

They weren’t just there for fun — no, this dynamic duo had one mission: win the grand prize of {money} 
to fund {enhance} injections for the witch, who insisted her crow’s feet were “a national emergency.”'

With her cat’s charm and a few potions up her sleeve, they were ready to slay — both the competition and the wrinkles.
'''

print(story)

# Shift to using the DEF function, instead of using print.

def generate_mad_lib(adj, w_name, clothing, c_name, verb, money, enhance):
    """Generates a Mad Lib story about a witch and her talking cat."""
    story = f'''
Mad Lib: "Witch & Whiskers: The Botox Heist"

Once upon a {adj} night, a witch named {w_name} dusted off her best {clothing} and headed to the Annual Cat Convention. 
Her sleek black cat, {c_name}, who could {verb} and speak fluent sarcasm, strutted alongside her.

They weren’t just there for fun — no, this dynamic duo had one mission: win the grand prize of {money} 
to fund {enhance} injections for the witch, who insisted her crow’s feet were “a national emergency.”

With her cat’s charm and a few potions up her sleeve, they were ready to slay — both the competition and the wrinkles.
'''
    return story

# Mad Lib: User Inputs (same as before).
adj = input("Enter an adjective (e.g., spooky, glamorous): ")
w_name = input("Enter a witch's name (e.g., Grizelda, Moonshadow): ")
clothing = input("Enter an article of clothing (e.g., cloak, sequined hat): ")
c_name = input("Enter a cat's name (e.g., Midnight, Sir Hiss-a-lot): ")
verb = input("Enter a verb (e.g., dance, sing, twerk): ")
money = input("Enter an amount of money (e.g., $5,000, one million dollars): ")
enhance = input("Enter a body enhancement procedure (e.g., botox, lip filler): ")

# Ask for Inputs and Print the story.
print("Your Custom Mad Lib 🐈‍")
print(generate_mad_lib(adj, w_name, clothing, c_name, verb, money, enhance))



# Practice Day 4 Concepts.
# Generate a Haiku WITHOUT using the DEF function (using print).
# Haiku User Inputs.
season = input("Enter a season (e.g., autumn, spring): ")
emotion = input("Enter an emotion (e.g., longing, joy): ")
nature_item = input("Enter a natural item (e.g., leaf, river): ")
animal = input("Enter an animal (e.g., fox, sparrow): ")

# Haiku (Generated by ChatGPT)
haiku = f"""
Whispers of {season},  
Echoes filled with {emotion},  
{nature_item} and {animal}.
"""

print("🍃 Your Custom Haiku 🍃")
print(haiku)

# Generate a Haiku using the DEF function.
def generate_haiku(season, emotion, nature_item, animal):
    """Generates a 3-line haiku using the provided words."""
    haiku = f"""
{season} whispers low,  
{emotion} drips in still silence,  
{nature_item} greets the {animal}.
"""
    return haiku

# Haiku User Inputs.
season = input("Enter a season (e.g., autumn, spring): ")
emotion = input("Enter an emotion (e.g., longing, joy): ")
nature_item = input("Enter a natural item (e.g., leaf, river): ")
animal = input("Enter an animal (e.g., fox, sparrow): ")

# Generate and print Haiku.
print("🍃 Your Custom Haiku 🍃")
print(generate_haiku(season, emotion, nature_item, animal))

'''Code entered for a red line in JSON
{
    "editor.rulers": [79],
    "workbench.colorCustomizations": {
        "editorRuler.foreground": "#FF0000"
    },
    "terminal.integrated.commandsToSkipShell": [
        // Keep only terminal commands here if needed
    ]
}'''